ARG ELASTIC_VERSION

# https://www.docker.elastic.co/
FROM j0qql1f7.mirror.aliyuncs.com/kibana/kibana:${ELASTIC_VERSION}

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
