ARG ELASTIC_VERSION

# https://www.docker.elastic.co/
FROM j0qql1f7.mirror.aliyuncs.com/elasticsearch/elasticsearch:${ELASTIC_VERSION}

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
