ARG ELASTIC_VERSION

# https://www.docker.elastic.co/
FROM j0qql1f7.mirror.aliyuncs.com/logstash/logstash:${ELASTIC_VERSION}

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
